name: gate-seal
plugins:
  - name: vyper
  - name: infura

ethereum:
  default_network: local
  local:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura
      goerli:
        upstream_provider: infura
