name: gate-seal
plugins:
  - name: vyper
    version: 0.6.1
  - name: hardhat
    version: 0.6.0

ethereum:
  default_network: local
  local:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura

geth:
  ethereum:
    mainnet:
      uri: ${MAINNET_RPC_ENDPOINT}
