name: gate-seal

compiler:
  vyper:
    version: 0.4.1
    evm_version: cancun

ethereum:
  default_network: local
  local:
    default_provider: hardhat

hardhat:
  hardhat_config_file: ./hardhat.config.js
  fork:
    ethereum:
      hoodi:
        upstream_provider: infura
      mainnet:
        upstream_provider: infura
