name: gate-seal
plugins:
  - name: vyper
    version: 0.6.1
  - name: infura
    version: 0.6.1

ethereum:
  default_network: local
  local:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura
      goerli:
        upstream_provider: infura
