ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"
BLUEPRINT_ZERO_ADDRESS = "blueprint: zero address"
MIN_SEALABLES = 1
MAX_SEALABLES = 8

SECONDS_PER_DAY = 60 * 60 * 24
SECONDS_PER_WEEK = SECONDS_PER_DAY * 7
SECONDS_PER_MONTH = SECONDS_PER_DAY * 30
SECONDS_PER_YEAR = SECONDS_PER_DAY * 365

MIN_SEAL_DURATION_DAYS = 6
MIN_SEAL_DURATION_SECONDS = SECONDS_PER_DAY * MIN_SEAL_DURATION_DAYS

MAX_SEAL_DURATION_DAYS = 21
MAX_SEAL_DURATION_SECONDS = SECONDS_PER_DAY * MAX_SEAL_DURATION_DAYS

# New initial lifetime constraints (1 month - 1 year)
MIN_INITIAL_LIFETIME_SECONDS = SECONDS_PER_MONTH  # 1 month
MAX_INITIAL_LIFETIME_SECONDS = SECONDS_PER_YEAR   # 1 year

# Extension constraints
MAX_EXTENSIONS = 5

# Extension activation window (1 week - 1 month before expiry)
MIN_EXTENSION_ACTIVATION_WINDOW_SECONDS = SECONDS_PER_WEEK   # 1 week
MAX_EXTENSION_ACTIVATION_WINDOW_SECONDS = SECONDS_PER_MONTH  # 1 month

MAX_EXPIRY_PERIOD_DAYS = 365 * 3
MAX_EXPIRY_PERIOD_SECONDS = SECONDS_PER_DAY * MAX_EXPIRY_PERIOD_DAYS

MAX_PROLONGATIONS = 5
MAX_PROLONGATION_DURATION_DAYS = 180
MAX_PROLONGATION_DURATION_SECONDS = SECONDS_PER_DAY * MAX_PROLONGATION_DURATION_DAYS

MAINNET_ID = 1
GOERLI_ID = 5
HOLESKY_ID = 17000
HOODI_ID = 560048
